"""
Django settings for auth_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Try to import SAML dependencies
try:
    import saml2
    from saml2.saml import NAMEID_FORMAT_EMAILADDRESS
    SAML_IMPORTS_AVAILABLE = True
except ImportError:
    SAML_IMPORTS_AVAILABLE = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '192.168.64.1,127.0.0.1,localhost,secureauth.local,192.168.64.3').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
]

# Add SAML support only if available
try:
    import djangosaml2
    INSTALLED_APPS.append('djangosaml2')
    SAML_AVAILABLE = True
except ImportError:
    SAML_AVAILABLE = False

# Add django_extensions only if it's available (useful for development)
try:
    import django_extensions
    INSTALLED_APPS.append('django_extensions')
except ImportError:
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
]

# Add SAML middleware only if SAML is available
if SAML_AVAILABLE:
    MIDDLEWARE.append('djangosaml2.middleware.SamlSessionMiddleware')

MIDDLEWARE.extend([
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
])

ROOT_URLCONF = 'auth_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auth_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', 'sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'))
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Active Directory Integration Settings
AD_SERVER = os.getenv('AD_SERVER', 'ldap://your-ad-server.com')
AD_DOMAIN = os.getenv('AD_DOMAIN', 'your-domain.com')
AD_USERNAME = os.getenv('AD_USERNAME', 'service-account@your-domain.com')
AD_PASSWORD = os.getenv('AD_PASSWORD', '')
AD_SEARCH_BASE = os.getenv('AD_SEARCH_BASE', 'DC=your-domain,DC=com')
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

LOGIN_REDIRECT_URL = 'authentication:home'
LOGOUT_REDIRECT_URL = 'authentication:login'
LOGIN_URL = 'authentication:login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Initialize SAML_CONFIG as None by default
SAML_CONFIG = None
SAML_READY = False

def _get_xmlsec_binary_path():
    """
    Get the correct xmlsec1 binary path based on the environment.
    First checks environment variable, then tries to detect the correct path.
    """
    import shutil
    
    # First try the environment variable
    env_path = os.getenv('XMLSEC_BINARY')
    if env_path and os.path.exists(env_path):
        return env_path
    
    # Common paths to check
    possible_paths = [
        '/usr/bin/xmlsec1',              # Linux (Ubuntu/Debian/Docker)
        '/opt/homebrew/bin/xmlsec1',     # macOS (Homebrew)
        '/usr/local/bin/xmlsec1',        # macOS (alternative)
        'xmlsec1',                       # Try system PATH
    ]
    
    # Check each possible path
    for path in possible_paths:
        if path == 'xmlsec1':
            # Use shutil.which to check if it's in PATH
            found_path = shutil.which('xmlsec1')
            if found_path:
                return found_path
        elif os.path.exists(path):
            return path
    
    # If nothing found, return the environment variable (even if None)
    # This will let the error be handled by the SAML library
    return env_path

# SAML Configuration - Only configure if SAML is available and not in CI
if SAML_AVAILABLE and SAML_IMPORTS_AVAILABLE and not os.getenv('CI'):
    # Get SAML environment variables with defaults
    saml_entity_id = os.getenv('SAML_ENTITY_ID')
    saml_acs_url = os.getenv('SAML_ACS_URL')
    saml_sls_url = os.getenv('SAML_SLS_URL')
    
    # Check if xmlsec1 binary is available
    xmlsec_binary_path = _get_xmlsec_binary_path()
    
    # Only configure SAML if required environment variables are set AND xmlsec1 is available
    if all([saml_entity_id, saml_acs_url, saml_sls_url]) and xmlsec_binary_path:
        SAML_READY = True
        SAML_CONFIG = {
            'entityid': saml_entity_id,
            'description': 'E2IP IAM Lab SAML Service',
            'service': {
                'sp': {
                    'name': 'E2IP IAM Lab',
                    'name_id_format': NAMEID_FORMAT_EMAILADDRESS,
                    'endpoints': {
                        'assertion_consumer_service': [
                            (saml_acs_url, saml2.BINDING_HTTP_POST),
                        ],
                        'single_logout_service': [
                            (saml_sls_url, saml2.BINDING_HTTP_REDIRECT),
                        ],
                    },
                'force_authn': True,  # Always force fresh authentication
                'name_id_format_allow_create': True,
                'want_response_signed': True,  # Require signed responses for security
                'want_assertions_signed': True,  # Require signed assertions for security
                'want_assertions_or_response_signed': True,  # At least one must be signed
                'authn_requests_signed': False,  # We don't sign requests (can be enabled if needed)
                'logout_requests_signed': False,
                'allow_unsolicited': False,  # Disable IdP-initiated SSO to force fresh requests
                'only_use_keys_in_metadata': True,  # Use keys from metadata for security
                'disable_ssl_certificate_validation': True,  # For development only
            },
        },
        'debug': DEBUG,
        # Disable all signature verification
        'verify_ssl_cert': False,
        'xmlsec_binary': xmlsec_binary_path,
        }

        # Configure SAML with ADFS metadata file
        metadata_file = BASE_DIR / 'saml_metadata' / 'adfs_metadata.xml'
        if metadata_file.exists():
            SAML_CONFIG['metadata'] = {
                'local': [str(metadata_file)],
            }

        # SAML attribute mapping
        SAML_ATTRIBUTE_MAPPING = {
            'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress': ('email', 'username'),
            'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname': ('first_name',),
            'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname': ('last_name',),
            'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name': ('username',),
        }

        # SAML user creation settings
        SAML_CREATE_UNKNOWN_USER = True
        SAML_DJANGO_USER_MAIN_ATTRIBUTE = 'username'
        SAML_DJANGO_USER_MAIN_ATTRIBUTE_LOOKUP = '__iexact'

# Authentication backends
# Default authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Only add SAML backend if properly configured
if SAML_READY:
    try:
        import djangosaml2
        AUTHENTICATION_BACKENDS.append('djangosaml2.backends.Saml2Backend')
    except ImportError:
        pass

# Cookie security settings for SAML/SSO
# These settings ensure cookies work properly with SAML authentication over HTTPS
# In development, we need to be more lenient with cookie settings
DEBUG_MODE = DEBUG
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False' if DEBUG_MODE else 'True').lower() == 'true'
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax' if DEBUG_MODE else 'None')
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False' if DEBUG_MODE else 'True').lower() == 'true'
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax' if DEBUG_MODE else 'None')
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for debugging
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000', 'https://secureauth.local:8000', 'https://localhost:8000'] if DEBUG_MODE else []
CSRF_USE_SESSIONS = True  # Use session-based CSRF tokens
CSRF_COOKIE_AGE = 31449600  # 1 year

# Additional security settings for production
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# WebAuthn Configuration for MFA
WEBAUTHN_AVAILABLE = True
try:
    import webauthn
    WEBAUTHN_RP_ID = os.getenv('WEBAUTHN_RP_ID', '192.168.64.1')  # Should match your domain
    WEBAUTHN_RP_NAME = os.getenv('WEBAUTHN_RP_NAME', 'SecureAuth')
    WEBAUTHN_ORIGIN = os.getenv('WEBAUTHN_ORIGIN', 'https://192.168.64.1:8000')  # Default to HTTPS for development
    
    # For production, use your actual domain:
    # WEBAUTHN_RP_ID = 'yourdomain.com'
    # WEBAUTHN_ORIGIN = 'https://yourdomain.com'
    
except ImportError:
    WEBAUTHN_AVAILABLE = False
    print("Warning: WebAuthn library not installed. MFA functionality will be limited.")

# MFA Settings
MFA_BACKUP_CODE_LENGTH = 10  # Length of backup codes
MFA_BACKUP_CODE_COUNT = 8    # Number of backup codes to generate
MFA_CHALLENGE_TIMEOUT = 300  # MFA challenge timeout in seconds (5 minutes)

