services:
  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.linux
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
      - ../static:/app/static
    env_file:
      - ../.env


