# Generated by Django 4.2.23 on 2025-08-01 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.TextField(unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('transports', models.JSONField(default=list)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(default='security-key', max_length=50)),
                ('aaguid', models.CharField(blank=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMFAPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('backup_codes_generated', models.BooleanField(default=False)),
                ('last_backup_codes_generated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MFAChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.TextField()),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('challenge_type', models.CharField(choices=[('webauthn', 'WebAuthn/FIDO2'), ('backup', 'Backup Code')], default='webauthn', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFABackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFAAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('webauthn', 'WebAuthn/FIDO2'), ('backup', 'Backup Code'), ('registration', 'Device Registration')], max_length=20)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.webauthncredential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['user', 'is_active'], name='authenticat_user_id_3a7b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['credential_id'], name='authenticat_credent_b2eae4_idx'),
        ),
        migrations.AddIndex(
            model_name='mfachallenge',
            index=models.Index(fields=['session_key'], name='authenticat_session_a94cac_idx'),
        ),
        migrations.AddIndex(
            model_name='mfachallenge',
            index=models.Index(fields=['user', 'expires_at'], name='authenticat_user_id_5f5b77_idx'),
        ),
        migrations.AddIndex(
            model_name='mfabackupcode',
            index=models.Index(fields=['user', 'used'], name='authenticat_user_id_a9a092_idx'),
        ),
        migrations.AddIndex(
            model_name='mfabackupcode',
            index=models.Index(fields=['code'], name='authenticat_code_60ed3d_idx'),
        ),
        migrations.AddIndex(
            model_name='mfaattempt',
            index=models.Index(fields=['user', 'created_at'], name='authenticat_user_id_097be3_idx'),
        ),
        migrations.AddIndex(
            model_name='mfaattempt',
            index=models.Index(fields=['success', 'created_at'], name='authenticat_success_403d83_idx'),
        ),
    ]
