# Generated by Django 4.2.23 on 2025-08-04 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('mfa_setup', 'MFA Setup'), ('device_registered', 'Security Device Registered'), ('device_removed', 'Security Device Removed'), ('backup_codes_generated', 'Backup Codes Generated'), ('backup_code_used', 'Backup Code Used'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated'), ('settings_changed', 'Settings Changed'), ('failed_login', 'Failed Login Attempt'), ('failed_mfa', 'Failed MFA Attempt'), ('session_started', 'Session Started'), ('session_expired', 'Session Expired')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning'), ('info', 'Information')], default='success', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='authenticat_user_id_c8058a_idx'), models.Index(fields=['activity_type', 'created_at'], name='authenticat_activit_da8e3c_idx'), models.Index(fields=['status', 'created_at'], name='authenticat_status_0017fc_idx')],
            },
        ),
    ]
