# Generated by Django 4.2.23 on 2025-08-04 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('mfa_setup', 'MFA Setup'), ('device_registered', 'Security Device Registered'), ('device_removed', 'Security Device Removed'), ('backup_codes_generated', 'Backup Codes Generated'), ('backup_code_used', 'Backup Code Used'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated'), ('failed_login', 'Failed Login Attempt'), ('failed_mfa', 'Failed MFA Attempt'), ('session_started', 'Session Started'), ('session_ended', 'Session Ended')], max_length=50)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='authenticat_user_id_a95cac_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity_type', 'created_at'], name='authenticat_activit_e8d9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['ip_address', 'created_at'], name='authenticat_ip_addr_44a560_idx'),
        ),
    ]
