# Generated by Django 4.2.23 on 2025-09-02 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_activitylog_delete_useractivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('mfa_setup', 'MFA Setup'), ('device_registered', 'Security Device Registered'), ('device_removed', 'Security Device Removed'), ('totp_setup', 'TOTP Authenticator Setup'), ('totp_removed', 'TOTP Authenticator Removed'), ('backup_codes_generated', 'Backup Codes Generated'), ('backup_code_used', 'Backup Code Used'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated'), ('failed_login', 'Failed Login Attempt'), ('failed_mfa', 'Failed MFA Attempt'), ('session_started', 'Session Started'), ('session_ended', 'Session Ended')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mfaattempt',
            name='attempt_type',
            field=models.CharField(choices=[('webauthn', 'WebAuthn/FIDO2'), ('totp', 'TOTP'), ('backup', 'Backup Code'), ('registration', 'Device Registration')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mfachallenge',
            name='challenge_type',
            field=models.CharField(choices=[('webauthn', 'WebAuthn/FIDO2'), ('totp', 'TOTP'), ('backup', 'Backup Code')], default='webauthn', max_length=20),
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Authenticator App', max_length=100)),
                ('secret', models.CharField(max_length=32)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mfaattempt',
            name='totp_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.totpdevice'),
        ),
        migrations.AddIndex(
            model_name='totpdevice',
            index=models.Index(fields=['user', 'is_active'], name='authenticat_user_id_32df7b_idx'),
        ),
        migrations.AddIndex(
            model_name='totpdevice',
            index=models.Index(fields=['user', 'confirmed'], name='authenticat_user_id_82fffe_idx'),
        ),
    ]
