# Generated by Django 4.2.23 on 2025-09-04 08:59

import authentication.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_alter_activitylog_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('mfa_setup', 'MFA Setup'), ('device_registered', 'Security Device Registered'), ('device_removed', 'Security Device Removed'), ('totp_setup', 'TOTP Authenticator Setup'), ('totp_removed', 'TOTP Authenticator Removed'), ('backup_codes_generated', 'Backup Codes Generated'), ('backup_code_used', 'Backup Code Used'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated'), ('failed_login', 'Failed Login Attempt'), ('failed_mfa', 'Failed MFA Attempt'), ('session_started', 'Session Started'), ('session_ended', 'Session Ended'), ('document_uploaded', 'Document Uploaded'), ('document_downloaded', 'Document Downloaded'), ('document_accessed', 'Document Accessed'), ('document_updated', 'Document Updated'), ('document_deleted', 'Document Deleted')], max_length=50),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title or name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the document')),
                ('file', models.FileField(help_text='Upload your document (PDF, Word, Excel, PowerPoint, Images, etc.)', upload_to=authentication.models.user_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'xls', 'xlsx', 'ppt', 'pptx', 'csv', 'zip', 'rar', '7z', 'tar', 'gz'])])),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type of the file', max_length=50)),
                ('original_filename', models.CharField(help_text='Original filename', max_length=255)),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('financial', 'Financial'), ('legal', 'Legal'), ('medical', 'Medical'), ('education', 'Education'), ('other', 'Other')], default='personal', help_text='Document category', max_length=20)),
                ('is_private', models.BooleanField(default=True, help_text='Document is private to the user')),
                ('is_encrypted', models.BooleanField(default=False, help_text='Document is encrypted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='authenticat_user_id_5198af_idx'), models.Index(fields=['user', 'category'], name='authenticat_user_id_c6ca82_idx'), models.Index(fields=['user', 'is_private'], name='authenticat_user_id_647347_idx')],
            },
        ),
    ]
