name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py test

  build-linux:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multi-arch Linux image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.linux
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/secureauth:linux

  build-windows:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (Windows)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/secureauth:windows -f Dockerfile.windows .

      - name: Push Windows image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/secureauth:windows

  create-manifest:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push manifest
        run: |
          docker manifest create ${{ secrets.DOCKER_USERNAME }}/secureauth:latest \
            ${{ secrets.DOCKER_USERNAME }}/secureauth:linux \
            ${{ secrets.DOCKER_USERNAME }}/secureauth:windows

          # Annotate the manifest with platform details
          docker manifest annotate ${{ secrets.DOCKER_USERNAME }}/secureauth:latest \
            ${{ secrets.DOCKER_USERNAME }}/secureauth:linux --os linux
          docker manifest annotate ${{ secrets.DOCKER_USERNAME }}/secureauth:latest \
            ${{ secrets.DOCKER_USERNAME }}/secureauth:windows --os windows

          docker manifest push ${{ secrets.DOCKER_USERNAME }}/secureauth:latest
